### PR TITLE
Position independent amd64-51-30k amd64-64-24k

### PR DESCRIPTION
**Pull request by vtnerd**
This was initially PR'ed to the monero baseline, when @anonimal suggested a separate repo for the supercop code. This contains a base commit of files from supercop-20170904.tar which is apparently now outdated, but the relevant files here are unchanged. I then made the code `-fPIC` and `-fPIE` friendly.

@hyc @luigi1111 @smooth @othe @ArticMine @fluffypony @kenshi84 @knaccc

### CODE REVIEW

**Comment by anonimal** [comment]
Hi @vtnerd,

Referencing https://github.com/monero-project/monero/pull/2317.

An important bit that was overlooked:

>1. Either you or I would create a supercop repo and pull the respective bits we need from ed25519 into said repo's master branch. The needed changes are then done to a respective `monero` and `kovri` branch.

So, we should first initialize this repo not with a README but with the original supercop code (kept in master for easy file checksum comparison) and then this PR is based off master into a `monero` branch; exactly like https://github.com/monero-project/unbound (minus the SVN-to-Git). Once that's done, kovri will then pull from this repo and work from branch `kovri`.

How does that sound?

**Comment by vtnerd** [comment]
I don't see why having README files matters. Its trivial to ignore it when doing a folder comparison, especially since the primary concern is a comparison of the appropriate subdirectories. And I cannot issue a PR to github without an initial commit, so somebody with direct write access would have to commit the initial source code for me.

I also omitted large parts of the supercop code - the entire source is much larger and we are using a fraction of its contents. Do you think the entire source needs to be dumped into the repo? Seems like a waste to synchronize all of that content, but its not particularly difficult to do.

I will undo the relative addressing from this PR, I think you are correct that it should be in its own branch. Easier to keep upstream synchronized with that separation.

**Comment by anonimal** [comment]
>And I cannot issue a PR to github without an initial commit, so somebody with direct write access would have to commit the initial source code for me.

Ok, no worries then, either of us can PR the additions to/removal of the README.

>Do you think the entire source needs to be dumped into the repo?

No. Just what's needed. I'll PR any missing bits if needed.

>I will undo the relative addressing from this PR, I think you are correct that it should be in its own branch. Easier to keep upstream synchronized with that separation.

Awesome, thanks @vtnerd.

**Comment by vtnerd** [comment]
Probably shouldve bumped this, since removing one of the commits from the PR is not highlighted by the github UI.

**Pull request merged**
